server {
    listen 80;
    server_name cn.wdmarais.dev;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name cn.wdmarais.dev;

    ssl_certificate     /etc/letsencrypt/live/cn.wdmarais.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cn.wdmarais.dev/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    root  /var/www/cn-pages;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(css|js|json|svg|ico|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}
